## tag::1[]
== C-1 btcd mishandles witness size checking
Tags: `runtime`, Weaknesses: GHSA ID: {url-ghsa}GHSA-2chg-86hq-7w38[GHSA-2chg-86hq-7w38] 

.File {url-repo}{url-blob}HalbornCTF_Golang_Cosmos/go.mod#L59-L63[HalbornCTF_Golang_Cosmos/go.mod#L59-L63]
[source, go, %linenums]
----
include::{ctf-dir}HalbornCTF_Golang_Cosmos/go.mod[lines=59..63]
----

btcd before 0.23.2, as used in Lightning Labs lnd before 0.15.2-beta and other Bitcoin-related products, mishandles witness size checking.

=== Specific Go Packages Affected
github.com/btcsuite/btcd/wire

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== References

* https://nvd.nist.gov/vuln/detail/CVE-2022-44797
* https://github.com/lightningnetwork/lnd/issues/7002
* https://github.com/btcsuite/btcd/pull/1896
* https://github.com/btcsuite/btcd/releases/tag/v0.23.2
* https://github.com/lightningnetwork/lnd/releases/tag/v0.15.2-beta
* https://github.com/btcsuite/btcd/pull/1896/commits/f523d4ccaa5f34a2f761f16a05f5d6e6665b1168
* https://github.com/advisories/GHSA-2chg-86hq-7w38
* https://pkg.go.dev/vuln/GO-2022-1098

=== Recommendation

Consider alternatives of this dependency.

## end::1[]
## tag::2[]
== C-2 crossbeam-deque Data Race before v0.7.4 and v0.8.1

Tags: `runtime`, Weaknesses: {url-cwe}362.html[CWE-362], CVE ID: {url-nist}CVE-2021-32810[CVE-2021-32810], GHSA ID: {url-ghsa}GHSA-pqqp-xmhj-wgcw[GHSA-pqqp-xmhj-wgcw]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L1004-L1008[HalbornCTF_Rust_Substrate/Cargo.lock#L1004-L1008]
[source, rust, %linenums]
----
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=1004..1008]
----

In the affected version of this crate, the result of the race condition is that one or more tasks in the worker queue can be popped twice instead of other tasks that are forgotten and never popped. If tasks are allocated on the heap, this can cause double free and a memory leak. If not, this still can cause a logical bug.

Crates using `Stealer::steal`, `Stealer::steal_batch`, or `Stealer::steal_batch_and_pop` are affected by this issue.

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== Patches

This has been fixed in crossbeam-deque 0.8.1 and 0.7.4.

<RECOMMENDATION>

=== References



## end::2[]
## tag::3[]
== C-3 crossbeam-deque Data Race before v0.7.4 and v0.8.1

Tags: `runtime`, Weaknesses: {url-cwe}362.html[CWE-362], CVE ID: {url-nist}CVE-2021-32810[CVE-2021-32810], GHSA ID: {url-ghsa}GHSA-pqqp-xmhj-wgcw[GHSA-pqqp-xmhj-wgcw]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L1004-L1008[HalbornCTF_Rust_Substrate/Cargo.lock#L1004-L1008]
[source, rust, %linenums]
----
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=1004..1008]
----

In the affected version of this crate, the result of the race condition is that one or more tasks in the worker queue can be popped twice instead of other tasks that are forgotten and never popped. If tasks are allocated on the heap, this can cause double free and a memory leak. If not, this still can cause a logical bug.

Crates using `Stealer::steal`, `Stealer::steal_batch`, or `Stealer::steal_batch_and_pop` are affected by this issue.

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== Patches

This has been fixed in crossbeam-deque 0.8.1 and 0.7.4.

<RECOMMENDATION>

=== References



## end::3[]
## tag::4[]
== C-4 Overflow in libsecp256k1
Tags: `runtime`, Weaknesses: GHSA ID: {url-ghsa}GHSA-g4vj-x7v9-h82m[GHSA-g4vj-x7v9-h82m] {url-cwe}190.html[CWE-190], {url-cwe}347.html[CWE-347]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L2798-L2802[HalbornCTF_Rust_Substrate/Cargo.lock#L2798-L2802]
[source, rust, %linenums]
----
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=2798..2802]
----

An issue was discovered in the libsecp256k1 crate before 0.5.0 for Rust. It can verify an invalid signature because it allows the R or S parameter to be larger than the curve order, aka an overflow.

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== References

* https://nvd.nist.gov/vuln/detail/CVE-2021-38195
* https://github.com/paritytech/libsecp256k1/pull/67
* https://rustsec.org/advisories/RUSTSEC-2021-0076.html
* https://github.com/advisories/GHSA-g4vj-x7v9-h82m

=== Recommendation

Consider alternatives of this dependency.

## end::4[]
## tag::5[]
== C-5 Out of bounds write in nalgebra
Tags: `runtime`, Weaknesses: GHSA ID: {url-ghsa}GHSA-3w8g-xr3f-2mp8[GHSA-3w8g-xr3f-2mp8] {url-cwe}119.html[CWE-119], {url-cwe}787.html[CWE-787]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L3213-L3217[HalbornCTF_Rust_Substrate/Cargo.lock#L3213-L3217]
[source, rust, %linenums]
----
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=3213..3217]
----

The `Deserialize` implementation for `VecStorage` did not maintain the invariant that the number of elements must equal `nrows * ncols`. Deserialization of specially crafted inputs could allow memory access beyond allocation of the vector.

This flaw was introduced in v0.11.0 (https://github.com/dimforge/nalgebra/commit/086e6e719f53fecba6dadad2e953a487976387f5[`086e6e`]) due to the addition of an automatically derived implementation of `Deserialize` for `MatrixVec`. `MatrixVec` was later renamed to `VecStorage` in v0.16.13 (https://github.com/dimforge/nalgebra/commit/0f66403cbbe9eeac15cedd8a906c0d6a3d8841f2[`0f66403`]) and continued to use the automatically derived implementation of `Deserialize`.

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== References

* https://nvd.nist.gov/vuln/detail/CVE-2021-38190
* https://github.com/dimforge/nalgebra/issues/883
* https://rustsec.org/advisories/RUSTSEC-2021-0070.html
* https://github.com/dimforge/nalgebra/pull/889
* https://github.com/dimforge/nalgebra/commit/a803271fcce75b7c151e92aa099dfa546db4adc5
* https://github.com/dimforge/nalgebra/blob/dev/CHANGELOG.md#0270
* https://github.com/advisories/GHSA-3w8g-xr3f-2mp8

=== Recommendation

Consider alternatives of this dependency.

## end::5[]
## tag::6[]
== C-6 Rust Failure Crate Vulnerable to Type confusion
Tags: `runtime`, Weaknesses: GHSA ID: {url-ghsa}GHSA-r98r-j25q-rmpr[GHSA-r98r-j25q-rmpr] {url-cwe}843.html[CWE-843]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L1408-L1412[HalbornCTF_Rust_Substrate/Cargo.lock#L1408-L1412]
[source, rust, %linenums]
----
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=1408..1412]
----

Safe Rust code can implement malfunctioning `__private_get_type_id__` and cause type confusion when downcasting, which is an undefined behavior.

Users who derive Fail trait are not affected.

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== References

* https://nvd.nist.gov/vuln/detail/CVE-2019-25010
* https://github.com/rust-lang-nursery/failure/issues/336
* https://rustsec.org/advisories/RUSTSEC-2019-0036.html
* https://github.com/advisories/GHSA-r98r-j25q-rmpr

=== Recommendation

Consider alternatives of this dependency.

## end::6[]
## tag::7[]
== C-7 Memory flaw in zeroize_derive
Tags: `runtime`, Weaknesses: GHSA ID: {url-ghsa}GHSA-c5hx-w945-j4pq[GHSA-c5hx-w945-j4pq] {url-cwe}459.html[CWE-459]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L8931-L8935[HalbornCTF_Rust_Substrate/Cargo.lock#L8931-L8935]
[source, rust, %linenums]
----
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=8931..8935]
----

An issue was discovered in the zeroize_derive crate before 1.1.1 for Rust. Dropped memory is not zeroed out for an enum.

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== References

* https://nvd.nist.gov/vuln/detail/CVE-2021-45706
* https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/zeroize_derive/RUSTSEC-2021-0115.md
* https://rustsec.org/advisories/RUSTSEC-2021-0115.html
* https://github.com/iqlusioninc/crates/issues/876
* https://github.com/advisories/GHSA-c5hx-w945-j4pq

=== Recommendation

Consider alternatives of this dependency.

## end::7[]
## tag::8[]
== C-8 Type confusion if __private_get_type_id__ is overriden
Tags: `runtime`, Weaknesses: GHSA ID: {url-ghsa}GHSA-jq66-xh47-j9f3[GHSA-jq66-xh47-j9f3] {url-cwe}843.html[CWE-843]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L1408-L1412[HalbornCTF_Rust_Substrate/Cargo.lock#L1408-L1412]
[source, rust, %linenums]
----
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=1408..1412]
----

An issue was discovered in the failure crate through 0.1.5 for Rust. It has a type confusion flaw when downcasting. NOTE: This vulnerability only affects products that are no longer supported by the maintainer.

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== References

* https://nvd.nist.gov/vuln/detail/CVE-2020-25575
* https://github.com/rust-lang-nursery/failure/issues/336
* https://github.com/RustCrypto/hashes/pull/91
* https://boats.gitlab.io/blog/post/failure-to-fehler/
* https://github.com/RustSec/advisory-db/blob/main/crates/failure/RUSTSEC-2019-0036.md
* https://rustsec.org/advisories/RUSTSEC-2019-0036.html
* https://rustsec.org/advisories/RUSTSEC-2020-0036.html
* https://github.com/advisories/GHSA-jq66-xh47-j9f3

=== Recommendation

Consider alternatives of this dependency.

## end::8[]
## tag::9[]
== C-9 Deserialization of Untrusted Data in rust-cpuid
Tags: `runtime`, Weaknesses: GHSA ID: {url-ghsa}GHSA-w428-f65r-h4q2[GHSA-w428-f65r-h4q2] {url-cwe}502.html[CWE-502]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L963-L967[HalbornCTF_Rust_Substrate/Cargo.lock#L963-L967]
[source, rust, %linenums]
----
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=963..967]
----

An issue was discovered in the raw-cpuid crate before 9.1.1 for Rust. If the serialize feature is used (which is not the the default), a Deserialize operation may lack sufficient validation, leading to memory corruption or a panic.

=== Impact: Critical 9.8 / 10

.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== References

* https://nvd.nist.gov/vuln/detail/CVE-2021-45687
* https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/raw-cpuid/RUSTSEC-2021-0089.md
* https://rustsec.org/advisories/RUSTSEC-2021-0089.html
* https://github.com/gz/rust-cpuid/issues/43
* https://github.com/advisories/GHSA-w428-f65r-h4q2

=== Recommendation

Consider alternatives of this dependency.

## end::9[]
