## tag::1[]
== C-1 btcd mishandles witness size checking
Tags: `runtime`, CVE ID: {url-nist}CVE-2022-44797[CVE-2022-44797], GHSA ID: {url-ghsa}GHSA-2chg-86hq-7w38[GHSA-2chg-86hq-7w38]

.File {url-repo}{url-blob}HalbornCTF_Golang_Cosmos/go.mod#L60
[source,go]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Golang_Cosmos/go.mod[lines=60]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

btcd before 0.23.2, as used in Lightning Labs lnd before 0.15.2-beta and other Bitcoin-related products, mishandles witness size checking.

=== Specific Go Packages Affected
github.com/btcsuite/btcd/wire

## end::1[]
## tag::2[]
== C-2 crossbeam-deque Data Race before v0.7.4 and v0.8.1
Tags: `runtime`, Weakness: {url-cwe}362.html[CWE-362], CVE ID: {url-nist}CVE-2021-32810[CVE-2021-32810], GHSA ID: {url-ghsa}GHSA-pqqp-xmhj-wgcw[GHSA-pqqp-xmhj-wgcw]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L1005
[source,rust]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=1004..1008]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== Impact

In the affected version of this crate, the result of the race condition is that one or more tasks in the worker queue can be popped twice instead of other tasks that are forgotten and never popped. If tasks are allocated on the heap, this can cause double free and a memory leak. If not, this still can cause a logical bug.

Crates using `Stealer::steal`, `Stealer::steal_batch`, or `Stealer::steal_batch_and_pop` are affected by this issue.

=== Patches

This has been fixed in crossbeam-deque 0.8.1 and 0.7.4.

=== Credits

This issue was reported and fixed by Maor Kleinberger.

=== License

This advisory is in the public domain.

## end::2[]
## tag::3[]
== C-3 crossbeam-deque Data Race before v0.7.4 and v0.8.1
Tags: `runtime`, Weakness: {url-cwe}362.html[CWE-362], CVE ID: {url-nist}CVE-2021-32810[CVE-2021-32810], GHSA ID: {url-ghsa}GHSA-pqqp-xmhj-wgcw[GHSA-pqqp-xmhj-wgcw]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L1005
[source,rust]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=1004..1008]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

=== Impact

In the affected version of this crate, the result of the race condition is that one or more tasks in the worker queue can be popped twice instead of other tasks that are forgotten and never popped. If tasks are allocated on the heap, this can cause double free and a memory leak. If not, this still can cause a logical bug.

Crates using `Stealer::steal`, `Stealer::steal_batch`, or `Stealer::steal_batch_and_pop` are affected by this issue.

=== Patches

This has been fixed in crossbeam-deque 0.8.1 and 0.7.4.

=== Credits

This issue was reported and fixed by Maor Kleinberger.

=== License

This advisory is in the public domain.

## end::3[]
## tag::4[]
== C-4 Overflow in libsecp256k1
Tags: `runtime`, Weakness: {url-cwe}190.html[CWE-190], {url-cwe}347.html[CWE-347], CVE ID: {url-nist}CVE-2021-38195[CVE-2021-38195], GHSA ID: {url-ghsa}GHSA-g4vj-x7v9-h82m[GHSA-g4vj-x7v9-h82m]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L3167
[source,rust]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=3166..3170]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

An issue was discovered in the libsecp256k1 crate before 0.5.0 for Rust. It can verify an invalid signature because it allows the R or S parameter to be larger than the curve order, aka an overflow.

## end::4[]
## tag::5[]
== C-5 Out of bounds write in nalgebra
Tags: `runtime`, Weakness: {url-cwe}119.html[CWE-119], {url-cwe}787.html[CWE-787], CVE ID: {url-nist}CVE-2021-38190[CVE-2021-38190], GHSA ID: {url-ghsa}GHSA-3w8g-xr3f-2mp8[GHSA-3w8g-xr3f-2mp8]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L3688
[source,rust]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=3687..3691]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

The `Deserialize` implementation for `VecStorage` did not maintain the invariant that the number of elements must equal `nrows * ncols`. Deserialization of specially crafted inputs could allow memory access beyond allocation of the vector.

This flaw was introduced in v0.11.0 (https://github.com/dimforge/nalgebra/commit/086e6e719f53fecba6dadad2e953a487976387f5[`086e6e`]) due to the addition of an automatically derived implementation of `Deserialize` for `MatrixVec`. `MatrixVec` was later renamed to `VecStorage` in v0.16.13 (https://github.com/dimforge/nalgebra/commit/0f66403cbbe9eeac15cedd8a906c0d6a3d8841f2[`0f66403`]) and continued to use the automatically derived implementation of `Deserialize`.

## end::5[]
## tag::6[]
== C-6 Rust Failure Crate Vulnerable to Type confusion
Tags: `runtime`, Weakness: {url-cwe}843.html[CWE-843], CVE ID: {url-nist}CVE-2019-25010[CVE-2019-25010], GHSA ID: {url-ghsa}GHSA-r98r-j25q-rmpr[GHSA-r98r-j25q-rmpr]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L1409
[source,rust]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=1408..1412]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

Safe Rust code can implement malfunctioning `__private_get_type_id__` and cause type confusion when downcasting, which is an undefined behavior.

Users who derive Fail trait are not affected.

## end::6[]
## tag::7[]
== C-7 Memory flaw in zeroize_derive
Tags: `runtime`, Weakness: {url-cwe}459.html[CWE-459], CVE ID: {url-nist}CVE-2021-45706[CVE-2021-45706], GHSA ID: {url-ghsa}GHSA-c5hx-w945-j4pq[GHSA-c5hx-w945-j4pq]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L8936
[source,rust]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=8935..8939]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

An issue was discovered in the zeroize_derive crate before 1.1.1 for Rust. Dropped memory is not zeroed out for an enum.

## end::7[]
## tag::8[]
== C-8 Type confusion if __private_get_type_id__ is overriden
Tags: `runtime`, Weakness: {url-cwe}843.html[CWE-843], CVE ID: {url-nist}CVE-2020-25575[CVE-2020-25575], GHSA ID: {url-ghsa}GHSA-jq66-xh47-j9f3[GHSA-jq66-xh47-j9f3]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L1409
[source,rust]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=1408..1412]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

An issue was discovered in the failure crate through 0.1.5 for Rust. It has a type confusion flaw when downcasting. NOTE: This vulnerability only affects products that are no longer supported by the maintainer.

## end::8[]
## tag::9[]
== C-9 Deserialization of Untrusted Data in rust-cpuid
Tags: `runtime`, Weakness: {url-cwe}502.html[CWE-502], CVE ID: {url-nist}CVE-2021-45687[CVE-2021-45687], GHSA ID: {url-ghsa}GHSA-w428-f65r-h4q2[GHSA-w428-f65r-h4q2]

.File {url-repo}{url-blob}HalbornCTF_Rust_Substrate/Cargo.lock#L5154
[source,rust]
---- 
++++ <.>
include::{ctf-dir}HalbornCTF_Rust_Substrate/Cargo.lock[lines=5153..5157]
++++
----

=== CVSS Score: 9.8/10
.CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H
[%header]
|===
2+| CVSS base metrics
| Attack vector | Network
| Attack complexity | Low
| Privileges required | None
| User interaction | None
| Scope | Unchange
| Confidentiality | High
| Integrity | High
| Availability  | High
|===

An issue was discovered in the raw-cpuid crate before 9.1.1 for Rust. If the serialize feature is used (which is not the the default), a Deserialize operation may lack sufficient validation, leading to memory corruption or a panic.

## end::9[]
