## tag::1[]

== I-1 Malicious `.DS_Store` file

I ran a dsstore parser <<2>> to extract the metadata from `/.DS_Store` binary file. I found that `/.DS_Store` file is a malicious file and has probably been tampered with. If you want to learn more about parsing the .DS_Store file and its security implications see article <<3>>.

[NOTE]
====
`.DS_Store` file can leak information about the structure of a users directory or server. This information can be used by an attacker to identify the directories and could even expose sensitive information like private keys.
====

Output from parsing `.DS_Store`:

[source,shell]
----
Count:  4
HalbornCTF_Rust_Substrate
HalbornCTF_Rust_Substrate
HalbornCTF_Rust_Substrate
HalbornCTF_Solidity_Ethereum
----

=== Impact

The content shows 3 directories of the same name `HalbornCTF_Rust_Substrate` followed by `HalbornCTF_Solidity_Ethereum` which contradicts what is currently present in this repository. This indicated with a **HIGH** probability that `.DS_Store` has a bug or a malicious actor could have tampered with this file. A file system is unlikely to have 3 directories with the same name store within the same directory. I ask you to follow my recommendations below to mitigate this vulnerability.

=== Recommendation

- Remove the `.DS_Store` file from the repository see http://stackoverflow.com/questions/1139762/ddg#1139797[stackoverflow example here].
- Create `.gitignore` file at the root of your repository and add `.DS_Store` to prevent it from being added to the repository in the future.
- Additionally use an https://git-scm.com/docs/githooks#update[update hook] to prevent certain files from being pushed to your repositories, see https://stackoverflow.com/a/4145628/1657610[stackoverflow example here]. This can prevent anyone from force pushing a file even if it has already been included in your `.gitignore`.
- I recommend that anyone working on this project to take pre-cautions by working in an isolated virtual enviroment to prevent exposing your system files to malicious third parties who could also try to comprimise your system when sharing code.

## end::1[]
